
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Jan  7 2025 02:59:55 EST (Jan  7 2025 07:59:55 UTC)

// Verification Directory fv/day_trading 

module day_trading(clk, rst, stock_in, action_out);
  input clk, rst;
  input [15:0] stock_in;
  output [15:0] action_out;
  wire clk, rst;
  wire [15:0] stock_in;
  wire [15:0] action_out;
  wire [2:0] trend_master;
  wire [4:0] day1_master;
  wire [4:0] day3_master;
  wire [2:0] current_state_slave;
  wire [4:0] day2_master;
  wire [2:0] next_state_master;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_163, n_164, n_165, n_166, n_168, n_188, n_189, n_190;
  wire owned_master;
  assign action_out[4] = 1'b0;
  assign action_out[5] = 1'b0;
  assign action_out[6] = 1'b0;
  assign action_out[7] = 1'b0;
  assign action_out[8] = 1'b0;
  assign action_out[9] = 1'b0;
  assign action_out[10] = 1'b0;
  assign action_out[11] = 1'b0;
  assign action_out[12] = 1'b0;
  assign action_out[13] = 1'b0;
  assign action_out[14] = 1'b0;
  assign action_out[15] = 1'b0;
  latch_c_1x \trend_master_reg[0] (.ph (n_168), .d (n_189), .q
       (trend_master[0]));
  latch_c_1x \trend_master_reg[2] (.ph (n_168), .d (n_166), .q
       (trend_master[2]));
  a2o1_1x g7516__4296(.a (n_165), .b (trend_master[2]), .c (n_163), .y
       (n_166));
  latch_c_1x \trend_master_reg[1] (.ph (n_168), .d (n_164), .q
       (trend_master[1]));
  nand2_1x g7518__3772(.a (n_76), .b (n_161), .y (n_164));
  nor3_1x g7519__1474(.a (n_157), .b (n_160), .c (n_152), .y (n_163));
  a2o1_1x g7520__9682(.a (n_158), .b (n_150), .c (n_160), .y (n_161));
  and2_1x g7521__2683(.a (n_158), .b (n_155), .y (n_159));
  a2o1_1x g7522__1309(.a (n_61), .b (n_106), .c (n_156), .y (n_157));
  nor2_1x g7523__6877(.a (n_154), .b (n_153), .y (n_156));
  nand2_1x g7524__2900(.a (n_154), .b (n_153), .y (n_155));
  a2o1_1x g7525__2391(.a (n_148), .b (n_149), .c (n_151), .y (n_158));
  inv_1x g7528(.a (n_151), .y (n_152));
  or2_1x g7529__7675(.a (n_149), .b (n_148), .y (n_150));
  nor2_1x g7531__7118(.a (n_72), .b (n_147), .y (n_153));
  a2o1_1x g7530__8757(.a (n_142), .b (n_23), .c (n_60), .y (n_151));
  latch_c_1x \action_out_reg[2] (.ph (n_168), .d (n_146), .q
       (action_out[2]));
  latch_c_1x \action_out_reg[0] (.ph (n_168), .d (n_144), .q
       (action_out[0]));
  latch_c_1x \action_out_reg[1] (.ph (n_168), .d (n_145), .q
       (action_out[1]));
  inv_1x g7535(.a (n_149), .y (n_147));
  nand2_1x g7537__1786(.a (n_190), .b (n_141), .y (n_148));
  nand3_1x g7532__5953(.a (n_105), .b (n_80), .c (n_123), .y (n_146));
  latch_c_1x \action_out_reg[3] (.ph (n_168), .d (n_133), .q
       (action_out[3]));
  latch_c_1x \day1_master_reg[2] (.ph (n_168), .d (n_136), .q
       (day1_master[2]));
  latch_c_1x \day1_master_reg[3] (.ph (n_168), .d (n_135), .q
       (day1_master[3]));
  latch_c_1x \day1_master_reg[4] (.ph (n_168), .d (n_134), .q
       (day1_master[4]));
  a2o1_1x g7536__5703(.a (n_121), .b (n_54), .c (n_88), .y (n_145));
  a2o1_1x g7541__7114(.a (n_104), .b (n_81), .c (n_132), .y (n_144));
  a2o1_1x g7538__5266(.a (n_120), .b (n_20), .c (n_71), .y (n_149));
  latch_c_1x \day1_master_reg[1] (.ph (n_168), .d (n_138), .q
       (day1_master[1]));
  latch_c_1x \day1_master_reg[0] (.ph (n_168), .d (n_139), .q
       (day1_master[0]));
  nand3_1x g7544__2250(.a (n_119), .b (n_78), .c (n_190), .y (n_154));
  latch_c_1x \day3_master_reg[4] (.ph (n_168), .d (n_124), .q
       (day3_master[4]));
  latch_c_1x \day3_master_reg[0] (.ph (n_168), .d (n_129), .q
       (day3_master[0]));
  latch_c_1x \day3_master_reg[2] (.ph (n_168), .d (n_126), .q
       (day3_master[2]));
  latch_c_1x \day3_master_reg[3] (.ph (n_168), .d (n_125), .q
       (day3_master[3]));
  latch_c_1x \current_state_slave_reg[0] (.ph (n_140), .d (n_118), .q
       (current_state_slave[0]));
  a2o1_1x g7540__6083(.a (n_107), .b (n_12), .c (n_38), .y (n_142));
  nor3_1x g7543__2703(.a (n_115), .b (n_87), .c (n_77), .y (n_141));
  latch_c_1x owned_master_reg(.ph (n_168), .d (n_130), .q
       (owned_master));
  latch_c_1x \current_state_slave_reg[1] (.ph (n_140), .d (n_116), .q
       (current_state_slave[1]));
  latch_c_1x \day3_master_reg[1] (.ph (n_168), .d (n_128), .q
       (day3_master[1]));
  latch_c_1x \current_state_slave_reg[2] (.ph (n_140), .d (n_122), .q
       (current_state_slave[2]));
  a2o1_1x g7583__5795(.a (n_137), .b (stock_in[10]), .c (n_103), .y
       (n_139));
  a2o1_1x g7584__7344(.a (n_137), .b (stock_in[11]), .c (n_102), .y
       (n_138));
  a2o1_1x g7585__1840(.a (n_137), .b (stock_in[12]), .c (n_100), .y
       (n_136));
  a2o1_1x g7586__5019(.a (n_137), .b (stock_in[13]), .c (n_99), .y
       (n_135));
  a2o1_1x g7587__1857(.a (n_137), .b (stock_in[14]), .c (n_98), .y
       (n_134));
  latch_c_1x \day2_master_reg[3] (.ph (n_168), .d (n_110), .q
       (day2_master[3]));
  a2o1_1x g7539__9906(.a (n_131), .b (action_out[3]), .c (n_97), .y
       (n_133));
  a2o1_1x g7557__8780(.a (n_131), .b (action_out[0]), .c (n_82), .y
       (n_132));
  latch_c_1x \day2_master_reg[1] (.ph (n_168), .d (n_113), .q
       (day2_master[1]));
  latch_c_1x \day2_master_reg[2] (.ph (n_168), .d (n_112), .q
       (day2_master[2]));
  latch_c_1x \day2_master_reg[0] (.ph (n_168), .d (n_108), .q
       (day2_master[0]));
  latch_c_1x \day2_master_reg[4] (.ph (n_168), .d (n_109), .q
       (day2_master[4]));
  a2o1_1x g7582__4296(.a (n_137), .b (stock_in[15]), .c (n_89), .y
       (n_130));
  a2o1_1x g7577__3772(.a (n_127), .b (stock_in[0]), .c (n_93), .y
       (n_129));
  a2o1_1x g7578__1474(.a (n_127), .b (stock_in[1]), .c (n_92), .y
       (n_128));
  a2o1_1x g7579__4547(.a (n_127), .b (stock_in[2]), .c (n_96), .y
       (n_126));
  a2o1_1x g7580__9682(.a (n_127), .b (stock_in[3]), .c (n_95), .y
       (n_125));
  a2o1_1x g7581__2683(.a (n_127), .b (stock_in[4]), .c (n_90), .y
       (n_124));
  nand2_1x g7572__1309(.a (action_out[2]), .b (n_131), .y (n_123));
  and2_1x g7571__6877(.a (n_117), .b (next_state_master[2]), .y
       (n_122));
  mux2_c_1x g7558__2900(.d0 (action_out[1]), .d1 (n_69), .s
       (current_state_slave[2]), .y (n_121));
  nand2_1x g7559__2391(.a (n_36), .b (n_91), .y (n_120));
  a2o1_1x g7568__7675(.a (n_86), .b (n_16), .c (n_114), .y (n_119));
  and2_1x g7569__7118(.a (n_117), .b (next_state_master[0]), .y
       (n_118));
  and2_1x g7570__8757(.a (n_117), .b (next_state_master[1]), .y
       (n_116));
  nor2_1x g7590__1786(.a (n_25), .b (n_114), .y (n_115));
  a2o1_1x g7573__5953(.a (n_111), .b (stock_in[6]), .c (n_70), .y
       (n_113));
  a2o1_1x g7574__5703(.a (n_111), .b (stock_in[7]), .c (n_75), .y
       (n_112));
  a2o1_1x g7575__7114(.a (n_111), .b (stock_in[8]), .c (n_83), .y
       (n_110));
  a2o1_1x g7576__5266(.a (n_111), .b (stock_in[9]), .c (n_67), .y
       (n_109));
  a2o1_1x g7588__2250(.a (n_111), .b (stock_in[5]), .c (n_68), .y
       (n_108));
  nand2_1x g7589__6083(.a (n_106), .b (n_66), .y (n_107));
  nand3_1x g7542__2703(.a (n_104), .b (trend_master[1]), .c
       (trend_master[0]), .y (n_105));
  and2_1x g7604__5795(.a (day1_master[0]), .b (n_101), .y (n_103));
  and2_1x g7605__7344(.a (day1_master[1]), .b (n_101), .y (n_102));
  and2_1x g7606__1840(.a (day1_master[2]), .b (n_101), .y (n_100));
  and2_1x g7607__5019(.a (day1_master[3]), .b (n_101), .y (n_99));
  and2_1x g7608__1857(.a (day1_master[4]), .b (n_101), .y (n_98));
  and2_1x g7556__9906(.a (n_27), .b (n_104), .y (n_97));
  and2_1x g7600__8780(.a (day3_master[2]), .b (n_94), .y (n_96));
  and2_1x g7594__4296(.a (day3_master[3]), .b (n_94), .y (n_95));
  latch_c_1x \next_state_master_reg[1] (.ph (n_168), .d (n_59), .q
       (next_state_master[1]));
  latch_c_1x \next_state_master_reg[2] (.ph (n_168), .d (n_62), .q
       (next_state_master[2]));
  and2_1x g7598__3772(.a (day3_master[0]), .b (n_94), .y (n_93));
  and2_1x g7599__1474(.a (day3_master[1]), .b (n_94), .y (n_92));
  nand3_1x g7591__4547(.a (n_64), .b (n_6), .c (n_21), .y (n_91));
  and2_1x g7602__9682(.a (day3_master[4]), .b (n_94), .y (n_90));
  nor2_1x g7603__2683(.a (n_73), .b (n_65), .y (n_89));
  and2_1x g7610__1309(.a (action_out[1]), .b (n_84), .y (n_88));
  nor2_1x g7615__6877(.a (n_86), .b (n_85), .y (n_87));
  latch_c_1x \next_state_master_reg[0] (.ph (n_168), .d (n_58), .q
       (next_state_master[0]));
  a2o1_1x g7623__2900(.a (day2_master[1]), .b (n_17), .c (n_85), .y
       (n_114));
  or2_1x g7625__2391(.a (n_137), .b (n_84), .y (n_131));
  and2_1x g7613__7675(.a (day2_master[3]), .b (n_74), .y (n_83));
  nor3_1x g7592__7118(.a (n_79), .b (owned_master), .c (n_81), .y
       (n_82));
  a2o1_1x g7597__8757(.a (n_28), .b (n_26), .c (n_79), .y (n_80));
  inv_1x g7609(.a (n_77), .y (n_78));
  nand2_1x g7611__1786(.a (trend_master[1]), .b (n_165), .y (n_76));
  and2_1x g7612__5953(.a (day2_master[2]), .b (n_74), .y (n_75));
  nor3_1x g7593__5703(.a (n_79), .b (n_73), .c (trend_master[2]), .y
       (n_104));
  nor3_1x g7619__7114(.a (n_37), .b (n_71), .c (n_63), .y (n_72));
  and2_1x g7616__5266(.a (day2_master[1]), .b (n_74), .y (n_70));
  nor3_1x g7617__2250(.a (n_35), .b (n_49), .c (n_47), .y (n_69));
  and2_1x g7618__6083(.a (day2_master[0]), .b (n_74), .y (n_68));
  and2_1x g7614__2703(.a (day2_master[4]), .b (n_74), .y (n_67));
  a2o1_1x g7621__5795(.a (n_44), .b (day3_master[0]), .c (n_45), .y
       (n_66));
  inv_1x g7632(.a (n_65), .y (n_101));
  a2o1_1x g7626__1840(.a (n_11), .b (n_7), .c (n_63), .y (n_64));
  nand2_1x g7627__5019(.a (n_160), .b (n_53), .y (n_62));
  nor3_1x g7620__1857(.a (n_39), .b (n_43), .c (n_60), .y (n_61));
  nand2_1x g7629__9906(.a (n_48), .b (n_160), .y (n_84));
  nor3_1x g7622__8780(.a (n_56), .b (n_57), .c (day2_master[2]), .y
       (n_77));
  or2_1x g7635__4296(.a (n_111), .b (n_137), .y (n_59));
  a2o1_1x g7634__3772(.a (n_42), .b (n_117), .c (n_46), .y (n_58));
  a2o1_1x g7636__1474(.a (day2_master[2]), .b (n_57), .c (n_56), .y
       (n_85));
  nor2_1x g7639__4547(.a (n_51), .b (n_55), .y (n_65));
  or2_1x g7631__9682(.a (n_50), .b (n_55), .y (n_94));
  nand2_1x g7630__2683(.a (current_state_slave[2]), .b (n_54), .y
       (n_79));
  inv_1x g7649(.a (n_53), .y (n_127));
  a2o1_1x g7637__6877(.a (n_29), .b (n_117), .c (n_51), .y (n_165));
  a2o1_1x g7638__2900(.a (n_8), .b (n_117), .c (n_50), .y (n_74));
  and2_1x g7642__2391(.a (trend_master[2]), .b (n_81), .y (n_49));
  nand2_1x g7643__7675(.a (n_4), .b (n_51), .y (n_48));
  and2_1x g7644__7118(.a (n_73), .b (n_34), .y (n_47));
  nor2_1x g7641__8757(.a (current_state_slave[0]), .b (n_30), .y
       (n_46));
  a2o1_1x g7651__1786(.a (day3_master[2]), .b (n_31), .c (n_18), .y
       (n_45));
  nor2_1x g7650__5953(.a (day1_master[0]), .b (n_43), .y (n_44));
  nor2_1x g7647__5703(.a (rst), .b (n_32), .y (n_55));
  and2_1x g7648__7114(.a (n_51), .b (n_42), .y (n_111));
  a2o1_1x g7654__2250(.a (day1_master[0]), .b (n_24), .c (n_38), .y
       (n_39));
  nand2_1x g7652__6083(.a (n_9), .b (n_36), .y (n_37));
  nor3_1x g7633__2703(.a (n_34), .b (n_73), .c (trend_master[2]), .y
       (n_35));
  a2o1_1x g7655__5795(.a (day2_master[4]), .b (n_33), .c (n_19), .y
       (n_56));
  nand2_1x g7658__7344(.a (n_51), .b (n_32), .y (n_53));
  a2o1_1x g7656__1840(.a (day2_master[2]), .b (n_31), .c (n_22), .y
       (n_63));
  or2_1x g7657__5019(.a (n_30), .b (n_29), .y (n_160));
  and2_1x g7659__1857(.a (n_50), .b (n_32), .y (n_137));
  nand2_1x g7645__9906(.a (trend_master[2]), .b (n_27), .y (n_28));
  nand3_1x g7653__8780(.a (n_3), .b (n_73), .c (n_14), .y (n_26));
  and2_1x g7646__4296(.a (current_state_slave[0]), .b (n_50), .y
       (n_54));
  and2_1x g7666__3772(.a (day2_master[0]), .b (n_24), .y (n_25));
  or2_1x g7662__1474(.a (n_33), .b (day1_master[4]), .y (n_23));
  nor2_1x g7664__4547(.a (n_10), .b (day1_master[1]), .y (n_22));
  or2_1x g7665__9682(.a (n_31), .b (day2_master[2]), .y (n_21));
  nand2_1x g7661__2683(.a (n_13), .b (day1_master[4]), .y (n_20));
  nor2_1x g7667__1309(.a (n_15), .b (day3_master[3]), .y (n_19));
  nor2_1x g7660__6877(.a (n_17), .b (day1_master[1]), .y (n_18));
  or2_1x g7679__2900(.a (n_24), .b (day2_master[0]), .y (n_16));
  nand2_1x g7669__2391(.a (n_15), .b (day3_master[3]), .y (n_40));
  nand2_1x g7670__7675(.a (n_57), .b (day1_master[2]), .y (n_106));
  and2_1x g7672__7118(.a (day1_master[4]), .b (n_33), .y (n_60));
  and2_1x g7673__8757(.a (day1_master[1]), .b (n_17), .y (n_43));
  and2_1x g7674__1786(.a (trend_master[1]), .b (n_14), .y (n_34));
  inv_1x g7677(.a (n_50), .y (n_30));
  nor2_1x g7668__5953(.a (n_13), .b (day1_master[4]), .y (n_71));
  nand2_1x g7682__5703(.a (n_5), .b (day3_master[3]), .y (n_12));
  nand2_1x g7663__7114(.a (n_10), .b (day1_master[1]), .y (n_11));
  nand2_1x g7678__5266(.a (n_1), .b (day2_master[0]), .y (n_9));
  inv_1x g7675(.a (n_42), .y (n_8));
  nand2_1x g7681__2250(.a (n_0), .b (day1_master[0]), .y (n_7));
  nand2_1x g7680__6083(.a (n_15), .b (day1_master[3]), .y (n_6));
  nor2_1x g7683__2703(.a (n_5), .b (day3_master[3]), .y (n_38));
  nand2_1x g7684__5795(.a (n_10), .b (day3_master[1]), .y (n_86));
  or2_1x g7685__7344(.a (n_4), .b (current_state_slave[0]), .y (n_29));
  nand2_1x g7671__1840(.a (n_5), .b (day2_master[3]), .y (n_36));
  inv_1x g7676(.a (n_27), .y (n_81));
  nand2_1x g7687__5019(.a (clk), .b (n_117), .y (n_140));
  and2_1x g7686__1857(.a (current_state_slave[0]), .b (n_4), .y (n_32));
  and2_1x g7689__9906(.a (n_117), .b (current_state_slave[1]), .y
       (n_51));
  nand2_2x g7692__8780(.a (n_2), .b (n_117), .y (n_168));
  nor2_1x g7688__4296(.a (current_state_slave[0]), .b
       (current_state_slave[2]), .y (n_42));
  nor2_1x g7690__3772(.a (trend_master[1]), .b (trend_master[0]), .y
       (n_27));
  nor2_1x g7691__1474(.a (rst), .b (current_state_slave[1]), .y (n_50));
  inv_1x g7703(.a (trend_master[2]), .y (n_3));
  inv_1x g7708(.a (day2_master[4]), .y (n_13));
  inv_1x g7705(.a (current_state_slave[2]), .y (n_4));
  inv_1x g7696(.a (day3_master[0]), .y (n_24));
  inv_1x g7694(.a (day3_master[2]), .y (n_57));
  inv_1x g7701(.a (day2_master[3]), .y (n_15));
  inv_1x g7693(.a (day2_master[1]), .y (n_10));
  inv_1x g7704(.a (owned_master), .y (n_73));
  inv_1x g7706(.a (clk), .y (n_2));
  inv_1x g7695(.a (day1_master[0]), .y (n_1));
  inv_1x g7700(.a (day2_master[0]), .y (n_0));
  inv_1x g7699(.a (trend_master[0]), .y (n_14));
  inv_1x g7702(.a (day3_master[1]), .y (n_17));
  inv_1x g7697(.a (day1_master[3]), .y (n_5));
  inv_1x g7707(.a (day1_master[2]), .y (n_31));
  inv_1x g7698(.a (day3_master[4]), .y (n_33));
  inv_1x g7709(.a (rst), .y (n_117));
  mux2_c_1x g2(.d0 (n_188), .d1 (trend_master[0]), .s (n_165), .y
       (n_189));
  nor2_2x g3(.a (n_159), .b (rst), .y (n_188));
  fulladder g7739(.a (day2_master[4]), .b (n_40), .c (n_33), .cout
       (n_190), .s (UNCONNECTED));
endmodule

