set_db port:day_trading/clk .original_name {clk}
set_db port:day_trading/rst .original_name {rst}
set_db {port:day_trading/stock_in[15]} .original_name {stock_in[15]}
set_db {port:day_trading/stock_in[14]} .original_name {stock_in[14]}
set_db {port:day_trading/stock_in[13]} .original_name {stock_in[13]}
set_db {port:day_trading/stock_in[12]} .original_name {stock_in[12]}
set_db {port:day_trading/stock_in[11]} .original_name {stock_in[11]}
set_db {port:day_trading/stock_in[10]} .original_name {stock_in[10]}
set_db {port:day_trading/stock_in[9]} .original_name {stock_in[9]}
set_db {port:day_trading/stock_in[8]} .original_name {stock_in[8]}
set_db {port:day_trading/stock_in[7]} .original_name {stock_in[7]}
set_db {port:day_trading/stock_in[6]} .original_name {stock_in[6]}
set_db {port:day_trading/stock_in[5]} .original_name {stock_in[5]}
set_db {port:day_trading/stock_in[4]} .original_name {stock_in[4]}
set_db {port:day_trading/stock_in[3]} .original_name {stock_in[3]}
set_db {port:day_trading/stock_in[2]} .original_name {stock_in[2]}
set_db {port:day_trading/stock_in[1]} .original_name {stock_in[1]}
set_db {port:day_trading/stock_in[0]} .original_name {stock_in[0]}
set_db {port:day_trading/action_out[15]} .original_name {action_out[15]}
set_db {port:day_trading/action_out[14]} .original_name {action_out[14]}
set_db {port:day_trading/action_out[13]} .original_name {action_out[13]}
set_db {port:day_trading/action_out[12]} .original_name {action_out[12]}
set_db {port:day_trading/action_out[11]} .original_name {action_out[11]}
set_db {port:day_trading/action_out[10]} .original_name {action_out[10]}
set_db {port:day_trading/action_out[9]} .original_name {action_out[9]}
set_db {port:day_trading/action_out[8]} .original_name {action_out[8]}
set_db {port:day_trading/action_out[7]} .original_name {action_out[7]}
set_db {port:day_trading/action_out[6]} .original_name {action_out[6]}
set_db {port:day_trading/action_out[5]} .original_name {action_out[5]}
set_db {port:day_trading/action_out[4]} .original_name {action_out[4]}
set_db {port:day_trading/action_out[3]} .original_name {action_out[3]}
set_db {port:day_trading/action_out[2]} .original_name {action_out[2]}
set_db {port:day_trading/action_out[1]} .original_name {action_out[1]}
set_db {port:day_trading/action_out[0]} .original_name {action_out[0]}



set_db {pin:day_trading/trend_master_reg[0]/q} .original_name {trend_master[0]/q}
set_db {pin:day_trading/trend_master_reg[2]/q} .original_name {trend_master[2]/q}
set_db {pin:day_trading/trend_master_reg[1]/q} .original_name {trend_master[1]/q}
set_db {pin:day_trading/action_out_reg[2]/q} .original_name {action_out[2]/q}
set_db {pin:day_trading/action_out_reg[0]/q} .original_name {action_out[0]/q}
set_db {pin:day_trading/action_out_reg[1]/q} .original_name {action_out[1]/q}
set_db {pin:day_trading/action_out_reg[3]/q} .original_name {action_out[3]/q}
set_db {pin:day_trading/day1_master_reg[2]/q} .original_name {day1_master[2]/q}
set_db {pin:day_trading/day1_master_reg[3]/q} .original_name {day1_master[3]/q}
set_db {pin:day_trading/day1_master_reg[4]/q} .original_name {day1_master[4]/q}
set_db {pin:day_trading/day1_master_reg[1]/q} .original_name {day1_master[1]/q}
set_db {pin:day_trading/day1_master_reg[0]/q} .original_name {day1_master[0]/q}
set_db {pin:day_trading/day3_master_reg[4]/q} .original_name {day3_master[4]/q}
set_db {pin:day_trading/day3_master_reg[0]/q} .original_name {day3_master[0]/q}
set_db {pin:day_trading/day3_master_reg[2]/q} .original_name {day3_master[2]/q}
set_db {pin:day_trading/day3_master_reg[3]/q} .original_name {day3_master[3]/q}
set_db {pin:day_trading/current_state_slave_reg[0]/q} .original_name {current_state_slave[0]/q}
set_db pin:day_trading/owned_master_reg/q .original_name {owned_master/q}
set_db {pin:day_trading/current_state_slave_reg[1]/q} .original_name {current_state_slave[1]/q}
set_db {pin:day_trading/day3_master_reg[1]/q} .original_name {day3_master[1]/q}
set_db {pin:day_trading/current_state_slave_reg[2]/q} .original_name {current_state_slave[2]/q}
set_db {pin:day_trading/day2_master_reg[3]/q} .original_name {day2_master[3]/q}
set_db {pin:day_trading/day2_master_reg[1]/q} .original_name {day2_master[1]/q}
set_db {pin:day_trading/day2_master_reg[2]/q} .original_name {day2_master[2]/q}
set_db {pin:day_trading/day2_master_reg[0]/q} .original_name {day2_master[0]/q}
set_db {pin:day_trading/day2_master_reg[4]/q} .original_name {day2_master[4]/q}
set_db {pin:day_trading/next_state_master_reg[1]/q} .original_name {next_state_master[1]/q}
set_db {pin:day_trading/next_state_master_reg[2]/q} .original_name {next_state_master[2]/q}
set_db {pin:day_trading/next_state_master_reg[0]/q} .original_name {next_state_master[0]/q}
