vpx set dofile abort exit
vpx set screen display -noprogress
tclmode

# Generated by Genus(TM) Synthesis Solution 17.24-s038_1, revision 1.275d
# Generated on: Tue Jan 07 02:59:56 EST 2025 (Tue Jan 07 07:59:56 GMT 2025)

set lec_version [regsub {(-).} $env(LEC_VERSION) ""]

tcl_set_command_name_echo on

set_log_file trader_logs_Jan07-02:59:50/intermediate2final.lec.log -replace

usage -auto -elapse

set_verification_information fv_map_day_trading_mv_db

read_implementation_information fv/day_trading -golden fv_map -revised day_trading_mv

set_parallel_option -threads 4 -license "xl lp gxl lpgxl eco ecogxl" -norelease_license

set env(RC_VERSION)     "17.24-s038_1"
set env(CDN_SYNTH_ROOT) "/escnfs/home/csesoft/cadence/installs/GENUS172/tools.lnx86"
set CDN_SYNTH_ROOT      "/escnfs/home/csesoft/cadence/installs/GENUS172/tools.lnx86"
set env(CW_DIR) "/escnfs/home/csesoft/cadence/installs/GENUS172/tools.lnx86/lib/chipware"
set CW_DIR      "/escnfs/home/csesoft/cadence/installs/GENUS172/tools.lnx86/lib/chipware"

# default is to error out when module definitions are missing
set_undefined_cell black_box -noascend -both

add_search_path . -library -both
read_library -liberty -both   /escnfs/courses/fa24-cse-30342.01/dropbox/mjohns79/VLSI/lab5solo/muddlib.lib

read_design -verilog95   -golden -lastmod -noelab fv/day_trading/fv_map.v.gz
elaborate_design -golden -root {day_trading}

read_design -verilog95   -revised -lastmod -noelab trader_outputs_Jan07-02:59:50/day_trading_m.v
elaborate_design -revised -root {day_trading}

#add_name_alias fv/day_trading/fv_map.singlebit.original_name.alias.json.gz -golden
#set_mapping_method -alias -golden

report_design_data
report_black_box

set_flatten_model -seq_constant
set_flatten_model -seq_constant_x_to 0
set_flatten_model -nodff_to_dlat_zero
set_flatten_model -nodff_to_dlat_feedback
set_flatten_model -hier_seq_merge

#add_name_alias fv/day_trading/day_trading_mv.singlebit.original_name.alias.json.gz -revised
#set_mapping_method -alias -revised
#add_renaming_rule r1alias _reg((\\\[%w\\\])*(/U\\\$%d)*)$ @1 -type dff -both

set_analyze_option -auto

set_system_mode lec
report_unmapped_points -summary
report_unmapped_points -extra -unreachable -notmapped
add_compared_points -all
compare

report_compare_data -class nonequivalent -class abort -class notcompared
report_verification -verbose
report_statistics

write_verification_information
report_verification_information

tclmode
puts "No of compare points = [get_compare_points -count]"
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
puts "No of abort points   = [get_compare_points -abort -count]"
puts "No of unknown points = [get_compare_points -unknown -count]"
if {[get_compare_points -count] == 0} {
    puts "---------------------------------"
    puts "ERROR: No compare points detected"
    puts "---------------------------------"
}
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
}
if {[get_compare_points -abort -count] > 0} {
    puts "-----------------------------"
    puts "ERROR: Abort Points detected "
    puts "-----------------------------"
}
if {[get_compare_points -unknown -count] > 0} {
    puts "----------------------------------"
    puts "ERROR: Unknown Key Points detected"
    puts "----------------------------------"
}
vpxmode
exit -f
